# Hematopoiesis application: use of BoNesis for selection of components

---------

## Table of content

[**Data preprocessing**](#datapreprocess)
1. [Import the observations built from single-cell data.](#import)
2. [Standardize the observations' gene names.](#standardobs)
3. [Get interaction graph from DoRothEA database.](#dorothea)

[**Use of BoNesis for selection of components**](#bonesis)

---------

## Data preprocessing <a class="anchor" id="datapreprocess"></a>

### 1. Import the observations built from single-cell data: <a class="anchor" id="import"></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_nesto = pd.read_csv("../data/nestorowa_singlecell_binarized_observations.csv", sep=",", index_col=[0])

In [3]:
df_nesto

,1110008L16Rik,1110059E24Rik,1200007C13Rik,1300017J02Rik,1500005C15Rik,1600014C10Rik,1600020E01Rik,1700006J14Rik,1700017B05Rik,1700024P16Rik,...,Zscan21,Zscan22,Zscan29,Zswim3,Zswim4,Zufsp,Zxdb,Zxdc,Zyx,Zzz3
S1,0,0,NaN,NaN,NaN,0,0,0,0,NaN,...,0,0,0,NaN,NaN,0,NaN,NaN,1,0
S4,0,1,NaN,NaN,NaN,1,0,0,0,NaN,...,0,0,0,NaN,NaN,0,NaN,NaN,1,0
S0,0,1,NaN,NaN,NaN,0,0,0,0,NaN,...,0,0,0,NaN,NaN,0,NaN,NaN,1,0
S2,0,0,NaN,NaN,NaN,1,1,0,0,NaN,...,0,0,0,NaN,NaN,0,NaN,NaN,1,0
S5,0,0,NaN,NaN,NaN,0,0,1,0,NaN,...,0,0,0,NaN,NaN,0,NaN,NaN,1,0
S3,0,0,NaN,NaN,NaN,0,0,0,1,NaN,...,0,0,0,NaN,NaN,0,NaN,NaN,1,1

In [4]:
observations_from_singlecell_nestorowa = df_nesto.to_dict(orient="index")

In [5]:
observations_from_singlecell_nestorowa

{'S1': {'1110008L16Rik': 0,
  '1110059E24Rik': 0,
  '1200007C13Rik': nan,
  '1300017J02Rik': nan,
  '1500005C15Rik': nan,
  '1600014C10Rik': 0,
  '1600020E01Rik': 0,
  '1700006J14Rik': 0,
  '1700017B05Rik': 0,
  '1700024P16Rik': nan,
  '1700028E10Rik': nan,
  '1700029J07Rik': nan,
  '1700030K09Rik': 0,
  '1700065D16Rik': nan,
  '1700066M21Rik': nan,
  '1700096K18Rik': nan,
  '1810010H24Rik': nan,
  '1810011H11Rik': nan,
  '2010300C02Rik': nan,
  '2010315B03Rik': 0,
  '2210016F16Rik': 0,
  '2210016L21Rik': 0,
  '2310057M21Rik': 0,
  '2510009E07Rik': nan,
  '2610008E11Rik': nan,
  '2610021A01Rik': 0,
  '2610035D17Rik': 0,
  '2610044O15Rik8': 0,
  '2610301B20Rik': 0,
  '2610307P16Rik': 0,
  '2700029L08Rik': nan,
  '2810013P06Rik': 0,
  '2810021J22Rik': nan,
  '2810029C07Rik': nan,
  '2810414N06Rik': nan,
  '2810428J06Rik': nan,
  '2810468N07Rik': nan,
  '2810474O19Rik': 0,
  '2900005J15Rik': nan,
  '2900018N21Rik': nan,
  '2900092N22Rik': nan,
  '3110043O21Rik': nan,
  '3632451O06Rik': nan,
  '4632404H12Rik': nan,
  '4632427E13Rik': 0,
  '4732440D04Rik': nan,
  '4833407H14Rik': nan,
  '4833439L19Rik': 0,
  '4921507P07Rik': nan,
  '4922502D21Rik': nan,
  '4930431P03Rik': nan,
  '4930502E18Rik': nan,
  '4930522L14Rik': 0,
  '4930525G20Rik': nan,
  '4930539E08Rik': nan,
  '4930550C14Rik': nan,
  '4930555A03Rik': 0,
  '4930563E22Rik': nan,
  '4931406C07Rik': 0,
  '4933404O12Rik': nan,
  '4933416C03Rik': nan,
  '4933424M12Rik': nan,
  '5430403G16Rik': nan,
  '5430420F09Rik': nan,
  '5430427O19Rik': 0,
  '5730409E04Rik': nan,
  '5730455P16Rik': 0,
  '5830405F06Rik': nan,
  '5830418P13Rik': nan,
  '5830462I19Rik': nan,
  '6330403K07Rik': nan,
  '6330403L08Rik': nan,
  '6330408A02Rik': nan,
  '6720464F23Rik': nan,
  '6720489N17Rik': nan,
  '6820402A03Rik': nan,
  '8430408G22Rik': nan,
  '8430419K02Rik': nan,
  '9030407P20Rik': nan,
  '9030617O03Rik': nan,
  '9030619P08Rik': 1,
  '9130011E15Rik': nan,
  '9130019O22Rik': nan,
  '9130023H24Rik': nan,
  '9230109A22Rik': nan,
  '9230112E08Rik': nan,
  '9330175E14Rik': nan,
  '9330179D12Rik': nan,
  '9330182L06Rik': nan,
  '9430015G10Rik': 0,
  '9530068E07Rik': 0,
  '9530082P21Rik': 0,
  '9630010A21Rik': nan,
  '9930012K11Rik': nan,
  'a': nan,
  'A130010J15Rik': nan,
  'A130014A01Rik': nan,
  'A230072E10Rik': nan,
  'A230107N01Rik': nan,
  'A330023F24Rik': nan,
  'A430033K04Rik': nan,
  'A430106G13Rik': nan,
  'A430110C17Rik': nan,
  'A530041M06Rik': nan,
  'A530083M17Rik': nan,
  'A530099J19Rik': nan,
  'A630023P12Rik': nan,
  'A630033H20Rik': nan,
  'A630035G10Rik': nan,
  'A630052C17Rik': nan,
  'A730011C13Rik': nan,
  'A730020E08Rik': nan,
  'A830080D01Rik': 0,
  'AA474408': 0.0,
  'Aacs': 0,
  'Aak1': nan,
  'Aar2': 0,
  'Aass': nan,
  'AB124611': nan,
  'Abat': nan,
  'Abca1': nan,
  'Abca4': nan,
  'Abcb10': 0,
  'Abcb4': 0,
  'Abcb8': 0,
  'Abcc1': 0,
  'Abcc10': nan,
  'Abcc3': nan,
  'Abcc5': 0,
  'Abcd1': 0,
  'Abcd2': nan,
  'Abcd3': 0,
  'Abce1': 0,
  'Abcf3': 0,
  'Abcg2': 1,
  'Abcg3': nan,
  'Abcg4': nan,
  'Abhd13': 0,
  'Abhd16a': 0,
  'Abhd17b': 0,
  'Abhd4': 0,
  'Abi1': 0,
  'Abi2': 0,
  'Abl1': 0,
  'Abl2': 0,
  'Ablim1': 0,
  'Abr': 0,
  'Abtb1': 0,
  'Abtb2': nan,
  'AC149090.1': nan,
  'Acaa2': 0,
  'Acad12': nan,
  'Acadsb': 0,
  'Acap1': 1,
  'Acbd5': 0,
  'Accs': 0,
  'Acer2': nan,
  'Acly': 0,
  'Acot11': nan,
  'Acot9': 0,
  'Acox1': 0,
  'Acox3': nan,
  'Acp2': 0,
  'Acp5': nan,
  'Acpp': nan,
  'Acsbg1': nan,
  'Acsl3': 0,
  'Acsl5': 0.0,
  'Acss1': 0,
  'Acss2': 0,
  'Acvr1': nan,
  'Acvr2a': nan,
  'Acy3': nan,
  'Ada': 0,
  'Adal': nan,
  'Adam11': nan,
  'Adam17': 0,
  'Adam19': nan,
  'Adam22': 1.0,
  'Adam33': nan,
  'Adam8': nan,
  'Adamts10': 0,
  'Adamts6': nan,
  'Adamtsl2': nan,
  'Adamtsl5': nan,
  'Adarb1': nan,
  'Adat1': 0,
  'Adck1': 0,
  'Adcy7': 0,
  'Add2': nan,
  'Adgra3': nan,
  'Adgrd1': nan,
  'Adgre1': nan,
  'Adgre4': nan,
  'Adgrg1': 1.0,
  'Adgrg3': 0,
  'Adgrg5': nan,
  'Adgrl4': 1,
  'Adipoq': nan,
  'Adk': 0,
  'Ado': 0,
  'Adora2a': nan,
  'Adora2b': nan,
  'Adprm': 0,
  'Adrb2': 0,
  'Adsl': 1,
  'Adssl1': 0,
  'Aebp1': nan,
  'Afap1l1': 1,
  'Afdn': nan,
  'Aff3': 0,
  'Aff4': 0,
  'Afg3l2': 0,
  'Agmo': nan,
  'Ago4': nan,
  'Agps': 0,
  'Agrn': nan,
  'Ahctf1': 0,
  'Ahcyl1': 0,
  'Ahcyl2': 0,
  'Ahnak': nan,
  'Ahr': nan,
  'Ahrr': nan,
  'AI467606': 0,
  'AI504432': 0,
  'AI506816': 0,
  'AI597479': 0,
  'AI854703': nan,
  'AI987944': 0,
  'Aif1': nan,
  'Aif1l': nan,
  'Aig1': 0,
  'Aim1': nan,
  'Aipl1': nan,
  'Ak1': nan,
  'Ak3': 0,
  'Ak4': nan,
  'Akain1': nan,
  'Akap12': nan,
  'Akap7': 0,
  'Akap8l': 1,
  'Akna': 0,
  'Akr1c12': nan,
  'Akr1c19': nan,
  'Akt3': 0,
  'Aktip': 0,
  'Alad': 0,
  'Alas1': 0,
  'Alb': nan,
  'Alcam': 0,
  'Aldh18a1': 0,
  'Aldh1a1': 0,
  'Aldh1a2': nan,
  'Aldh1a7': nan,
  'Aldh3a1': nan,
  'Aldh3a2': 0,
  'Aldh3b1': nan,
  'Aldh6a1': 0,
  'Aldh9a1': 0,
  'Aldoc': nan,
  'Alg11': 0,
  'Alg2': 0,
  'Alg9': 0,
  'Alkbh8': 0,
  'Alox5': nan,
  'Alpl': nan,
  'Als2cl': nan,
  'Amigo1': nan,
  'Amigo2': nan,
  'Amigo3': nan,
  'Amot': nan,
  'Ampd2': 0,
  'Ampd3': nan,
  'Amz1': nan,
  'Anapc2': 0,
  'Anapc4': 0,
  'Angpt1': 1,
  'Angptl2': nan,
  'Ank': 0,
  'Ankef1': nan,
  'Ankfy1': 0,
  'Ankle1': 0,
  'Ankrd13d': nan,
  'Ankrd16': 0,
  'Ankrd22': nan,
  'Ankrd27': 0,
  'Ankrd29': nan,
  'Ankrd33b': nan,
  'Ankrd44': 0,
  'Ankrd46': 0,
  'Ankrd50': nan,
  'Ankrd6': nan,
  'Ankrd63': nan,
  'Ankrd7': nan,
  'Anks3': 0,
  'Ankub1': nan,
  'Anln': 0,
  'Ano10': nan,
  'Ano6': 0,
  'Ano7': nan,
  'Antxr2': nan,
  'Anxa1': 1,
  'Anxa2': 0,
  'Anxa3': nan,
  'Anxa4': 1,
  'Anxa5': 1,
  'Anxa6': 0,
  'Anxa9': 0,
  'Ap1b1': 0,
  'Ap1g2': 0,
  'Ap1m1': 1,
  'Ap1s2': 0,
  'Ap3m2': nan,
  'Ap3s1': 0,
  'Ap5m1': 0,
  'Ap5z1': 0,
  'Apbb1': nan,
  'Apeh': 0,
  'Aph1b': nan,
  'Api5': 1,
  'Apln': nan,
  'Aplp2': 0,
  'Apobec1': 0,
  'Apoe': 1,
  'Apol9b': nan,
  'App': nan,
  'Appl1': 0,
  'Appl2': 0,
  'Aqp1': 0,
  'Aqp9': 0,
  'Arap1': 1,
  'Arc': nan,
  'Arcn1': 1,
  'Areg': nan,
  'Arf3': 0,
  'Arfgef2': 0,
  'Arg1': nan,
  'Arhgap1': 0,
  'Arhgap12': 1.0,
  'Arhgap15': 1,
  'Arhgap18': 0,
  'Arhgap19': nan,
  'Arhgap25': 0,
  'Arhgap27': 0,
  'Arhgap27os3': nan,
  'Arhgap28': nan,
  'Arhgap29': nan,
  'Arhgap4': 0,
  'Arhgdib': nan,
  'Arhgef16': nan,
  'Arhgef17': nan,
  'Arhgef18': 0,
  'Arhgef28': nan,
  'Arhgef3': 0,
  'Arhgef39': 0,
  'Arhgef5': nan,
  'Arhgef6': 1,
  'Arid2': 0,
  'Arid3b': nan,
  'Arid5a': 0,
  'Arl11': 0,
  'Arl6ip1': nan,
  'Arl6ip6': 0,
  'Arl8b': 0,
  'Armc7': nan,
  'Armc8': 0,
  'Armcx1': 0,
  'Armcx2': 0,
  'Armcx5': nan,
  'Armt1': 0,
  'Arntl': 0,
  'Arpp21': nan,
  'Arrdc1': 1,
  'Arrdc3': 0,
  'Arrdc4': nan,
  'Arsk': 0,
  'Art4': 0,
  'Arvcf': nan,
  'Arxes1': nan,
  'Asah1': 0,
  'Asah2': nan,
  'Asb13': 0,
  'Asb2': nan,
  'Asb3': 0,
  'Asb4': nan,
  'Asb5': nan,
  'Asb8': 0,
  'Asf1b': 0,
  'Ash1l': 0.0,
  'Asns': 0,
  'Asph': 0,
  'Asphd2': nan,
  'Aspm': 0,
  'Asprv1': nan,
  'Atad1': 0,
  'Atad2': 0,
  'Atf7': 0,
  'Atg12': 0,
  'Atg14': 0,
  'Atg16l1': 0,
  'Atg16l2': nan,
  'Atg4b': 0,
  'Atg7': 0,
  'Atl2': 0,
  'Atp10a': 0,
  'Atp11a': nan,
  'Atp11c': 0,
  'Atp13a1': 0,
  'Atp13a2': 1,
  'Atp1a3': nan,
  'Atp1b1': nan,
  'Atp1b2': 0,
  'Atp1b3': 1,
  'Atp2a3': 1,
  'Atp2b4': 1,
  'Atp4a': nan,
  'Atp5a1': nan,
  'Atp5b': nan,
  'Atp5f1': 0.0,
  'Atp5g1': nan,
  'Atp5g3': nan,
  'Atp6ap1': 0,
  'Atp6ap2': 0,
  'Atp6v0e2': nan,
  'Atp6v1a': 0,
  'Atp7a': nan,
  'Atp7b': 0,
  'Atp8a1': 0,
  'Atp8a2': nan,
  'Atp8b4': 0,
  'Atp9a': nan,
  'Atp9b': 0,
  'Atpif1': 0.0,
  'Atrn': 0,
  'AU041133': nan,
  'Aurka': 0,
  'Aurkb': 0,
  'AW112010': 1,
  'AW146154': nan,
  'AW549877': 0,
  'Axl': nan,
  'Azin1': 0,
  'B230219D22Rik': 0,
  'B230312C02Rik': nan,
  'B230354K17Rik': 0,
  'B2m': nan,
  'B3galnt1': nan,
  'B3galnt2': 0,
  'B3gnt3': nan,
  'B3gnt5': 0,
  'B430306N03Rik': nan,
  'B4galt4': 0,
  'B4galt6': 0,
  'B830012L14Rik': nan,
  'Bace1': 0,
  'Bace2': nan,
  'Bach2': nan,
  'Bag2': 0,
  'Baiap3': nan,
  'Bank1': nan,
  'Bap1': 0,
  'Batf2': 1.0,
  'Batf3': nan,
  'Baz2b': 0,
  'Bbs1': nan,
  'Bbs10': nan,
  'Bbs12': nan,
  'Bbs2': nan,
  'Bbs4': nan,
  'Bbs9': nan,
  'BC002059': nan,
  'BC005561': 0,
  'BC016579': nan,
  'BC017643': 0,
  'BC022960': nan,
  'BC026585': 0,
  'BC030336': nan,
  'BC030499': nan,
  'BC035044': 0,
  'BC043934': nan,
  'BC055308': nan,
  'Bcap29': 0,
  'Bcas3': 0,
  'Bcl11b': nan,
  'Bcl2': 0,
  'Bcl2l14': nan,
  'Bco2': nan,
  'Bdh2': nan,
  'BE692007': nan,
  'Bend4': nan,
  'Best1': nan,
  'Bgn': nan,
  'Bhlha15': nan,
  'Bhlhb9': 0,
  'Bhlhe40': nan,
  'Bicd1': 0,
  'Bicdl1': nan,
  'Bid': 0,
  'Bin2': 1.0,
  'Birc2': 0,
  'Birc3': 0,
  'Birc5': 0,
  'Bivm': nan,
  'Blcap': 0,
  'Blk': nan,
  'Blnk': nan,
  'Blvrb': nan,
  'Blzf1': 0,
  'Bmf': nan,
  'Bmi1': 0,
  'Bmp7': nan,
  'Bmp8a': nan,
  'Bmpr2': 0,
  'Bmt2': nan,
  'Boc': nan,
  'Bok': nan,
  'Bpgm': 0,
  'Bpifb5': nan,
  'Bpifc': 1.0,
  'Braf': 0,
  'Brat1': 0,
  'Brdt': nan,
  'Brms1l': 0,
  'Bsg': nan,
  'Bspry': nan,
  'Bst1': nan,
  'Btaf1': 0,
  'Btbd10': 0,
  'Btbd11': nan,
  'Btbd19': 0,
  'Btbd3': nan,
  'Btbd9': 0,
  'Btc': nan,
  'Btg1': 0,
  'Btg2': 0,
  'Btk': 0,
  'Btla': nan,
  'Btnl10': nan,
  'Btnl9': nan,
  'Btrc': 0,
  'Bub1': 0,
  'Bub1b': 0,
  'Bub3': 0.0,
  'Bysl': 0,
  'Bzw1': nan,
  'C030010L15Rik': nan,
  'C030034L19Rik': 0,
  'C130013H08Rik': nan,
  'C130023A14Rik': nan,
  'C130089K02Rik': 0,
  'C1qbp': nan,
  'C1rl': nan,
  'C230038L03Rik': nan,
  'C230062I16Rik': nan,
  'C230085N15Rik': nan,
  'C3': nan,
  'C330018D20Rik': 0,
  'C330027C09Rik': 0,
  'C530050E15Rik': nan,
  'C5ar1': nan,
  'C77080': nan,
  'C87436': nan,
  'Cables2': 0,
  'Cacfd1': 0,
  'Cacna1a': nan,
  'Cacna1b': nan,
  'Cacna1e': nan,
  'Cacna2d1': nan,
  'Cacnb2': 1.0,
  'Cacybp': nan,
  'Cad': 0,
  'Cadps2': nan,
  'Calcrl': 0,
  'Calhm2': nan,
  'Calr': nan,
  'Calu': 0,
  'Caly': nan,
  'Camk1': 0,
  'Camk1d': nan,
  'Camk2b': nan,
  'Camk2d': 1,
  'Camkk1': nan,
  'Camp': nan,
  'Camsap2': nan,
  'Cand2': nan,
  'Canx': nan,
  'Capg': 1,
  'Capn2': nan,
  'Capn5': 0,
  'Capn7': 0,
  'Car1': 0,
  'Car2': nan,
  'Car8': nan,
  'Car9': 0,
  'Card10': nan,
  'Card11': nan,
  'Card6': nan,
  'Carf': nan,
  'Carhsp1': 0,
  'Carns1': nan,
  'Casc4': nan,
  'Casd1': 0,
  'Casp1': 0,
  'Casp12': 1.0,
  'Casp2': 0,
  'Casp3': 0,
  'Casp4': 0,
  'Casp9': 0,
  'Cast': 0,
  'Cat': 1,
  'Catsperg1': nan,
  'Cav1': nan,
  'Cav2': nan,
  'Cbfa2t2': 0,
  'Cbfb': 0,
  'Cbx5': 0,
  'Cbx7': 0,
  'Ccdc102a': nan,
  'Ccdc112': 1.0,
  'Ccdc122': nan,
  'Ccdc136': nan,
  'Ccdc137': 0,
  'Ccdc141': nan,
  'Ccdc149': nan,
  'Ccdc155': nan,
  'Ccdc157': nan,
  'Ccdc158': nan,
  'Ccdc166': 0,
  'Ccdc17': nan,
  'Ccdc181': 0,
  'Ccdc184': nan,
  'Ccdc186': nan,
  'Ccdc50': 0,
  'Ccdc91': 0,
  'Ccdc93': nan,
  'Ccl2': nan,
  'Ccl28': nan,
  'Ccl3': 0,
  'Ccl4': 0,
  'Ccl5': nan,
  'Ccl6': nan,
  'Ccl9': 0,
  'Ccna2': 0,
  'Ccnb1': 0,
  'Ccnb2': 0,
  'Ccnb2-ps': nan,
  'Ccnd3': 1,
  'Ccne1': 0,
  'Ccne2': 0,
  'Ccnf': 0,
  'Ccng1': 1,
  'Ccng2': 0,
  'Ccr1': nan,
  'Ccr2': nan,
  'Ccr6': nan,
  'Ccr7': nan,
  'Ccr8': nan,
  'Ccr9': nan,
  'Ccrl2': nan,
  'Ccser1': nan,
  'Ccser2': nan,
  'Cct2': nan,
  'Cct3': nan,
  'Cct4': nan,
  'Cct5': nan,
  'Cct6a': nan,
  'Cct7': nan,
  'Cct8': nan,
  'Cd101': nan,
  'Cd177': nan,
  'Cd19': nan,
  'Cd1d1': 1,
  'Cd2': nan,
  'Cd200': nan,
  'Cd200r1': nan,
  'Cd22': nan,
  'Cd226': nan,
  'Cd244': nan,
  'Cd24a': nan,
  'Cd27': 1,
  'Cd274': nan,
  'Cd276': nan,
  'Cd28': nan,
  'Cd2ap': 0,
  'Cd300a': 0,
  'Cd300ld': nan,
  'Cd300lg': nan,
  'Cd33': nan,
  'Cd34': 1,
  'Cd36': nan,
  'Cd38': nan,
  'Cd3g': nan,
  'Cd4': nan,
  'Cd44': 1,
  'Cd48': 0,
  'Cd52': 0,
  'Cd53': 0,
  'Cd55': 0,
  'Cd6': nan,
  'Cd63': 1,
  'Cd63-ps': 1,
  'Cd68': nan,
  'Cd69': 0,
  'Cd7': nan,
  'Cd74': 1.0,
  'Cd79a': nan,
  'Cd79b': 0,
  'Cd81': nan,
  'Cd82': 0,
  'Cd83': nan,
  'Cd84': 1,
  'Cd86': nan,
  'Cd9': 1,
  'Cd93': 1,
  'Cd96': nan,
  'Cd99l2': nan,
  'Cdc14a': 0,
  'Cdc14b': nan,
  'Cdc20': 0,
  'Cdc25b': nan,
  'Cdc42ep4': 0,
  'Cdc42se2': 1,
  'Cdc45': 0,
  'Cdc6': 0,
  'Cdc7': 0,
  'Cdca3': 0,
  'Cdca4': 0,
  'Cdca5': 0,
  'Cdca7': 0,
  'Cdca8': 0,
  'Cdcp1': nan,
  'Cdh1': nan,
  'Cdh13': nan,
  'Cdh15': nan,
  'Cdh16': nan,
  'Cdh23': nan,
  'Cdip1': 0,
  'Cdk1': 0,
  'Cdk14': nan,
  'Cdk17': 0,
  'Cdk18': nan,
  'Cdk19': 0,
  'Cdk20': nan,
  'Cdk6': 0.0,
  'Cdkl5': 1.0,
  'Cdkn1a': nan,
  'Cdkn1c': nan,
  'Cds2': 0,
  'Cdt1': 0,
  'Ceacam1': nan,
  'Ceacam10': nan,
  'Cecr2': nan,
  'Cela1': 0,
  'Cenpa': 0,
  'Cenpe': 0,
  'Cenpf': 0,
  'Cenpi': 0,
  'Cenpk': 0,
  'Cenpl': 0,
  'Cenpo': 0,
  'Cep170b': nan,
  'Cep55': nan,
  'Cep68': 1,
  'Cep70': 0,
  'Cep83os': 0,
  'Cept1': 0,
  'Cerk': 0,
  'Cers4': 0,
  'Cers5': 0,
  'Cers6': nan,
  'Ces2g': 0,
  'Cfap43': 0,
  'Cfap74': nan,
  'Cfd': nan,
  'Cflar': 0,
  'Cfp': nan,
  'Cftr': nan,
  'Chac1': nan,
  'Champ1': 0,
  'Chchd10': 0,
  'Chchd2': nan,
  'Chd3os': nan,
  'Chd9': 1,
  'Chic1': nan,
  'Chil3': nan,
  'Chil5': nan,
  'Chka': 0,
  'Chl1': nan,
  'Chm': 0,
  'Chmp3': 0,
  'Chmp7': 0,
  'Chordc1': 1,
  'Chp1': 0,
  'Chpf': nan,
  'Chrnb1': 1.0,
  'Chrnb4': nan,
  'Chst1': nan,
  'Chst10': nan,
  'Chst11': nan,
  'Chst14': nan,
  'Chst15': 0,
  'Chst2': nan,
  'Chst3': nan,
  'Chuk': 0,
  'Ciita': nan,
  'Cipc': 0,
  'Cish': 0,
  'Cited4': 0,
  'Ckap2': 0,
  'Ckap2l': 0,
  'Ckap5': 0,
  'Ckb': nan,
  'Cks1b': 0,
  'Cks2': 0.0,
  'Clca3a1': nan,
  'Clcf1': nan,
  'Clcn3': 0,
  'Clcn4': 0,
  'Clcn5': nan,
  'Cldn12': nan,
  'Cldn13': nan,
  'Cldn15': nan,
  'Cldn3': nan,
  'Cldn4': nan,
  'Clec12a': 0,
  'Clec12b': nan,
  'Clec14a': nan,
  'Clec1a': nan,
  'Clec1b': nan,
  'Clec2i': nan,
  'Clec4b1': nan,
  'Clec4d': nan,
  'Clec4e': nan,
  'Clec5a': nan,
  'Clec9a': nan,
  'Clic4': 0,
  'Clic5': nan,
  'Clip3': nan,
  'Clmn': nan,
  'Cln5': 0,
  'Clock': nan,
  'Clptm1l': 0,
  'Clpx': 0,
  'Cltc': 1,
  'Clu': nan,
  'Cma1': nan,
  'Cmah': nan,
  'Cmpk2': 0,
  'Cmtm6': 0,
  'Cnih1': 0,
  'Cnn2': 1,
  'Cnn3': 0,
  'Cnot10': 0,
  'Cnot7': 0,
  'Cnp': 0,
  'Cnr1': nan,
  'Cnr2': nan,
  'Cnrip1': 0,
  'Cnst': nan,
  'Cntn1': nan,
  'Coa5': 0,
  'Cobll1': nan,
  'Cog6': 0,
  'Cog7': 0,
  'Col23a1': nan,
  'Col4a1': 1.0,
  'Col4a2': nan,
  'Col5a1': nan,
  'Col9a3': nan,
  'Colgalt1': 0,
  'Colq': nan,
  'Comt': 1,
  'Copb1': 0,
  'Copb2': 0,
  'Copg1': 0,
  'Copg2': 0,
  'Cops8': 1,
  'Coq8a': 0,
  'Coro1a': 1,
  'Coro2b': nan,
  'Coro7': 1,
  'Cox4i1': 0.0,
  'Cox6a1': nan,
  'Cox6a2': nan,
  'Cox6b1': nan,
  'Cox7a2': nan,
  'Cox7b': 0.0,
  'Cpa3': nan,
  'Cplx2': nan,
  'Cpne8': nan,
  'Cpox': 0,
  'Cpq': 0,
  'Cpt1a': 0,
  'Cpt2': 0,
  'Cptp': nan,
  'Cpvl': nan,
  'Cpxm1': nan,
  'Cracr2b': nan,
  'Crbn': 0,
  'Creb5': nan,
  'Crebrf': 0,
  'Creg1': nan,
  'Crip1': 0.0,
  'Crip2': nan,
  'Crisp3': nan,
  'Crispld1': nan,
  'Crispld2': nan,
  'Crk': 0,
  'Crlf3': 1,
  'Crnkl1': 0,
  'Crot': 0,
  'Cry2': 0,
  'Cryz': nan,
  'Cs': 0,
  'Csad': 0,
  'Cse1l': 0,
  'Csf1r': nan,
  'Csf2': nan,
  'Csf2rb': 0,
  'Csf2rb2': nan,
  'Csf3r': 0,
  'Csgalnact1': nan,
  'Csgalnact2': 0,
  'Csrp3': nan,
  'Cst3': nan,
  'Cst7': 0,
  'Cstf1': 0,
  'Cstf2': 0,
  'Ctbs': nan,
  'Ctc1': 0,
  'Ctdsp2': 1,
  'Ctla2a': 1,
  'Ctla2b': 1,
  'Ctnna1': 0,
  'Ctnnal1': nan,
  'Ctnnd2': nan,
  'Ctps': 0,
  'Ctps2': 0,
  'Ctr9': 0,
  'Ctsb': 1,
  'Ctsc': 0,
  'Ctsd': nan,
  'Ctse': nan,
  'Ctsf': 0,
  'Ctsg': 0,
  'Ctsh': nan,
  'Ctsl': 0,
  'Ctso': 1,
  'Ctss': 0,
  'Ctsw': nan,
  'Ctsz': 0,
  'Cttn': 0,
  'Ctu1': 0,
  'Cul2': 0,
  'Cul3': 0,
  'Cul4a': 1,
  'Cx3cl1': nan,
  'Cxcl10': nan,
  'Cxcl12': nan,
  'Cxcr3': nan,
  'Cxcr6': nan,
  'Cyb561': nan,
  'Cyb561d1': nan,
  'Cyb5d2': nan,
  'Cyb5r1': 0,
  'Cyb5r3': 0,
  'Cybb': nan,
  'Cyc1': 1,
  'Cyfip1': 0,
  'Cyfip2': nan,
  'Cyld': 0,
  'Cyp11a1': nan,
  'Cyp20a1': 0,
  'Cyp26b1': nan,
  'Cyp27a1': nan,
  'Cyp2d22': nan,
  'Cyp2j6': nan,
  'Cyp2j9': 0,
  'Cyp2r1': nan,
  'Cyp39a1': nan,
  'Cyp4b1': nan,
  'Cyp4f18': nan,
  'Cyp4v3': nan,
  'Cyp51': 0,
  'Cyp7b1': nan,
  'Cysltr1': nan,
  'Cyth3': 0,
  'Cyth4': 1,
  'Cytip': 0,
  'D10Wsu102e': 0,
  'D130040H23Rik': nan,
  'D1Ertd622e': 0,
  'D230025D16Rik': 0,
  'D3Ertd254e': nan,
  'D3Ertd751e': nan,
  'D630030B08Rik': nan,
  'D630039A03Rik': nan,
  'D930016D06Rik': nan,
  'D930020B18Rik': nan,
  'D930028M14Rik': nan,
  ...},
 'S4': {'1110008L16Rik': 0,
  '1110059E24Rik': 1,
  '1200007C13Rik': nan,
  '1300017J02Rik': nan,
  '1500005C15Rik': nan,
  '1600014C10Rik': 1,
  '1600020E01Rik': 0,
  '1700006J14Rik': 0,
  '1700017B05Rik': 0,
  '1700024P16Rik': nan,
  '1700028E10Rik': nan,
  '1700029J07Rik': nan,
  '1700030K09Rik': 0,
  '1700065D16Rik': nan,
  '1700066M21Rik': nan,
  '1700096K18Rik': nan,
  '1810010H24Rik': nan,
  '1810011H11Rik': nan,
  '2010300C02Rik': nan,
  '2010315B03Rik': 0,
  '2210016F16Rik': 1,
  '2210016L21Rik': 0,
  '2310057M21Rik': 0,
  '2510009E07Rik': nan,
  '2610008E11Rik': nan,
  '2610021A01Rik': 0,
  '2610035D17Rik': 0,
  '2610044O15Rik8': 0,
  '2610301B20Rik': 0,
  '2610307P16Rik': 0,
  '2700029L08Rik': nan,
  '2810013P06Rik': 0,
  '2810021J22Rik': nan,
  '2810029C07Rik': nan,
  '2810414N06Rik': nan,
  '2810428J06Rik': nan,
  '2810468N07Rik': nan,
  '2810474O19Rik': 0,
  '2900005J15Rik': nan,
  '2900018N21Rik': nan,
  '2900092N22Rik': nan,
  '3110043O21Rik': nan,
  '3632451O06Rik': nan,
  '4632404H12Rik': nan,
  '4632427E13Rik': 0,
  '4732440D04Rik': nan,
  '4833407H14Rik': nan,
  '4833439L19Rik': 0,
  '4921507P07Rik': nan,
  '4922502D21Rik': nan,
  '4930431P03Rik': nan,
  '4930502E18Rik': nan,
  '4930522L14Rik': 0,
  '4930525G20Rik': nan,
  '4930539E08Rik': nan,
  '4930550C14Rik': nan,
  '4930555A03Rik': 0,
  '4930563E22Rik': nan,
  '4931406C07Rik': 0,
  '4933404O12Rik': nan,
  '4933416C03Rik': nan,
  '4933424M12Rik': nan,
  '5430403G16Rik': nan,
  '5430420F09Rik': nan,
  '5430427O19Rik': 0,
  '5730409E04Rik': nan,
  '5730455P16Rik': 0,
  '5830405F06Rik': nan,
  '5830418P13Rik': nan,
  '5830462I19Rik': nan,
  '6330403K07Rik': nan,
  '6330403L08Rik': nan,
  '6330408A02Rik': nan,
  '6720464F23Rik': nan,
  '6720489N17Rik': nan,
  '6820402A03Rik': nan,
  '8430408G22Rik': nan,
  '8430419K02Rik': nan,
  '9030407P20Rik': nan,
  '9030617O03Rik': 1.0,
  '9030619P08Rik': 0,
  '9130011E15Rik': nan,
  '9130019O22Rik': nan,
  '9130023H24Rik': nan,
  '9230109A22Rik': nan,
  '9230112E08Rik': nan,
  '9330175E14Rik': nan,
  '9330179D12Rik': nan,
  '9330182L06Rik': nan,
  '9430015G10Rik': 0,
  '9530068E07Rik': 1,
  '9530082P21Rik': 0,
  '9630010A21Rik': nan,
  '9930012K11Rik': nan,
  'a': nan,
  'A130010J15Rik': nan,
  'A130014A01Rik': nan,
  'A230072E10Rik': nan,
  'A230107N01Rik': nan,
  'A330023F24Rik': nan,
  'A430033K04Rik': nan,
  'A430106G13Rik': nan,
  'A430110C17Rik': nan,
  'A530041M06Rik': nan,
  'A530083M17Rik': nan,
  'A530099J19Rik': nan,
  'A630023P12Rik': nan,
  'A630033H20Rik': nan,
  'A630035G10Rik': nan,
  'A630052C17Rik': nan,
  'A730011C13Rik': nan,
  'A730020E08Rik': nan,
  'A830080D01Rik': 0,
  'AA474408': nan,
  'Aacs': 0,
  'Aak1': nan,
  'Aar2': 0,
  'Aass': nan,
  'AB124611': nan,
  'Abat': nan,
  'Abca1': nan,
  'Abca4': nan,
  'Abcb10': 0,
  'Abcb4': 0,
  'Abcb8': 0,
  'Abcc1': 0,
  'Abcc10': nan,
  'Abcc3': nan,
  'Abcc5': 0,
  'Abcd1': 1,
  'Abcd2': 1.0,
  'Abcd3': 0,
  'Abce1': 1,
  'Abcf3': 0,
  'Abcg2': 0,
  'Abcg3': nan,
  'Abcg4': nan,
  'Abhd13': 0,
  'Abhd16a': 0,
  'Abhd17b': 1,
  'Abhd4': 0,
  'Abi1': 1,
  'Abi2': 0,
  'Abl1': 1,
  'Abl2': 0,
  'Ablim1': 0,
  'Abr': 1,
  'Abtb1': 0,
  'Abtb2': nan,
  'AC149090.1': nan,
  'Acaa2': 1,
  'Acad12': nan,
  'Acadsb': 0,
  'Acap1': 0,
  'Acbd5': 0,
  'Accs': 0,
  'Acer2': nan,
  'Acly': 1,
  'Acot11': nan,
  'Acot9': 1,
  'Acox1': 0,
  'Acox3': 1.0,
  'Acp2': 0,
  'Acp5': nan,
  'Acpp': nan,
  'Acsbg1': nan,
  'Acsl3': 0,
  'Acsl5': nan,
  'Acss1': 0,
  'Acss2': 0,
  'Acvr1': nan,
  'Acvr2a': nan,
  'Acy3': nan,

### 2. Standardize the observations' gene names. <a class="anchor" id="standardobs"></a>

We use the file "data/Mus_musculus.gene_info.202103.tsv" downloaded on 2021-03 from NCBI (mouse gene info).

In [7]:
import gene_name_standardization_copy as gns

c:\Users\leave\Documents\4A - Cours\Computational-Systems-Biology-of-Cancer---Project-\lea_notebooks\gene_name_standardization_copy.py:24: SyntaxWarning: invalid escape sequence '\|'
  command_parsing = "awk -F'\t' '{print $3 \"\t\" $5 \"\t\" $11}' " + path_NCBIgeneinfo + " | tr \| '\t' > " + path_NCBIgeneinfo_cut + " ; sed -i 1d " + path_NCBIgeneinfo_cut

In [8]:
#Use the metatdata gene matrix to standardize gene names in the binarized cell state matrix
standardized_observations = gns.observations_standardization(observations_from_singlecell_nestorowa, "../data/Mus_musculus.gene_info.202103.tsv")

In [9]:
# Visualisation of the matrix with standardized gene names:
df_standardized = pd.DataFrame.from_dict(standardized_observations, orient="index").fillna('')
df_standardized

,1110008L16RIK,1110059E24RIK,1200007C13RIK,1300017J02RIK,1500005C15RIK,1600014C10RIK,1600020E01RIK,1700006J14RIK,1700017B05RIK,1700024P16RIK,...,ZSCAN21,ZSCAN22,ZSCAN29,ZSWIM3,ZSWIM4,ZUFSP,ZXDB,ZXDC,ZYX,ZZZ3
S1,0,0,,,,0,0,0,0,,...,0,0,0,,,0,,,1,0
S4,0,1,,,,1,0,0,0,,...,0,0,0,,,0,,,1,0
S0,0,1,,,,0,0,0,0,,...,0,0,0,,,0,,,1,0
S2,0,0,,,,1,1,0,0,,...,0,0,0,,,0,,,1,0
S5,0,0,,,,0,0,1,0,,...,0,0,0,,,0,,,1,0
S3,0,0,,,,0,0,0,1,,...,0,0,0,,,0,,,1,1

In [10]:
# Genes being in this single-cell dataset:
standardized_genenames_in_singlecell = set(df_standardized)

In [11]:
len(standardized_genenames_in_singlecell)

4768

### 3. Get interaction graph from DoRothEA database. <a class="anchor" id="dorothea"></a>

Interactions of confidence A, B and C were extracted from DoRothEA on 2021-07-07. 
The extraction from DoRothEA and the standardization of the gene names were processed as described in the [tutorial](https://github.com/StephanieChevalier/notebooks_for_bonesis/blob/main/tutorials/Tutorial_for_interaction_graph_preprocessing.ipynb). 
We only kept edges from transcription factors to transcription factors or to genes with expression values in the Nestorowa single-cell dataset ([dorothea_ABC_20210707_TF.sif](https://github.com/StephanieChevalier/notebooks_for_bonesis/blob/main/applications/hematopoiesis/data/dorothea_ABC_20210707_TF.sif): 1001 nodes, 2777 edges).

## Use of BoNesis for selection of components <a class="anchor" id="bonesis"></a>

In [12]:
import bonesis

Apparently here to upload teh sif file you can go thruogh the dorothea python module. This requires installation of R and dorothea .py. See the tutorial.

In [ ]:
df = pd.read_csv("../data/dorothea_ABC_20210707_TF.sif", header=None, names=("in", "sign", "out"), sep="\t")
standardized_dorothea = nx.from_pandas_edgelist(df, "in", "out", ["sign"], nx.MultiDiGraph())
subgraph_from_selection = standardized_dorothea.subgraph(set(components))

In [19]:
#Convert tsv data from signor to sif format
import pandas as pd

df = pd.read_csv("data\\all_data_M_musculus_07_10_26.tsv", sep="\t")
# SIGNOR utilise 'ENTITYA', 'MECHANISM'/'EFFECT', et 'ENTITYB'
sif_df = df[["ENTITYA", "EFFECT", "ENTITYB"]]
#sif_df.to_csv("data\\signor_network.sif", sep="\t", index=False, header=False)

In [23]:
def df_to_interaction_graph(df):

    interaction_graph = []

    for _, row in df.iterrows():
        source = str(row["ENTITYA"]).strip()
        target = str(row["ENTITYB"]).strip()
        effect = str(row["EFFECT"]).strip().lower()

        # Vérification si la chaîne contient "up-regulates" ou "down-regulates"
        if "up-regulates" in effect or "activates" in effect:
            sign = 1
        elif "down-regulates" in effect or "inhibits" in effect:
            sign = -1
        else:
            # Si aucun des termes clés n'est trouvé dans le texte de l'effet
            continue

        interaction_graph.append((source, target, {"sign": sign}))

    return interaction_graph


# --- Utilisation ---
interaction_graph = df_to_interaction_graph(sif_df)

# Aperçu du résultat
print(interaction_graph[:5])

[('LYN', 'CD79B', {'sign': 1}), ('Fbxo44', 'Cullin 1-RBX1-Skp1', {'sign': 1}), ('NEK7', 'Eml4', {'sign': -1}), ('LPAR1', 'Gna14', {'sign': 1}), ('SRC', 'CASP9', {'sign': 1})]

In [25]:
#Standardize the gene names in the interaction graph using the same metadata gene matrix as for the single-cell dataset
stand_signor= gns.interaction_list_standardization(interaction_graph, "../data/Mus_musculus.gene_info.202103.tsv")
print(stand_signor[:5])

[('LYN', 'CD79B', {'sign': 1}), ('FBXO44', 'CULLIN 1-RBX1-SKP1', {'sign': 1}), ('NEK7', 'EML4', {'sign': -1}), ('LPAR1', 'GNA14', {'sign': 1}), ('SRC', 'CASP9', {'sign': 1})]

In [39]:
#Filter only on data that is in the scRNA seq dataset
filtered_signor = []

for source, target, attr in stand_signor:
    # On vérifie que la SOURCE ET la CIBLE sont dans le jeu de données scRNA-seq
    if source in standardized_genenames_in_singlecell and target in standardized_genenames_in_singlecell:
        filtered_signor.append((source, target, attr))

print(f"Nombre d'interactions initiales : {len(stand_signor)}")
print(f"Nombre d'interactions filtrées  : {len(filtered_signor)}")

Nombre d'interactions initiales : 37383
Nombre d'interactions filtrées  : 2955

In [40]:
interaction_graph = bonesis.InfluenceGraph(filtered_signor)

In [41]:
#INitialization of the research space for boolean networks
bo = bonesis.BoNesis(interaction_graph, standardized_observations)

In [42]:
print(f"domain: {len(interaction_graph.nodes())} nodes, {len(interaction_graph.edges())} edges")

domain: 1017 nodes, 2955 edges

### Dynamics
<img src="img/trajectoire.png" alt="nestorowa stream trajectory" style="width:40%;"/>

#### fixpoints

In [43]:
s2 = bo.fixed(~bo.obs("S2"))
s4 = bo.fixed(~bo.obs("S4"))
s5 = bo.fixed(~bo.obs("S5"))
s2 != s4
s5 != s4
s2 != s5;

#### positive reachability

In [44]:
~bo.obs('S1') >= ~bo.obs('S0') >= s2
~bo.obs('S0') >= ~bo.obs('S3') >= s4
~bo.obs('S3') >= s5;

#### negative reachability

In [45]:
~bo.obs("S3") / s2;

### Optimization & view

In [46]:
bo.maximize_nodes()
bo.maximize_strong_constants()

In [47]:
view = bonesis.NonStrongConstantNodesView(bo, mode="opt")

In [48]:
view.standalone(output_filename=f"maxnodes_maxstrongconstant.sh")

OverflowError: integer 35345263799 does not fit '32-bit int'